# Generated by Django 4.2.13 on 2024-05-16 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entitys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="pubdate",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 16, 17, 26, 4, 216719),
                verbose_name="Дата публикации",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 16, 22, 26, 4, 216719),
                verbose_name="Дата окончания",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 16, 17, 26, 4, 216719),
                verbose_name="Дата начала",
            ),
        ),
    ]
